name: Auto Close Milestone on Release

on:
  pull_request:
    branches: ['**']
  # release:
  #   types: [published]

jobs:
  close-milestone:
    runs-on: ubuntu-latest
    steps:
      - name: Close milestone
        run: |
            echo ref_name:
            echo ${{ github.ref_name }}
            MILESTONE_TITLE="test v0.1.0"
            MILESTONE_NUMBER=$(gh api milestones --jq ".[] | select(.title == \"$MILESTONE_TITLE\") | .number")

            if [ "$MILESTONE_NUMBER" != "null" ] && [ "$MILESTONE_NUMBER" != "" ]; then
                echo "Closing milestone: $MILESTONE_TITLE (ID: $MILESTONE_NUMBER)"
                gh api milestones/$MILESTONE_NUMBER -f state=closed
            else
                echo "No milestone found with title: $MILESTONE_TITLE"
            fi